### PR TITLE
Add reusable modal component

### PR DESCRIPTION
**Pull request by MuhammadTanveer94**

### CODE REVIEW

**Review by suryapratapsinghsuryavanshi — CHANGES_REQUESTED** [review]
I think you make some changes to open a popup with search result data.

**Comment by MuhammadTanveer94** [comment]
> I think you make some changes to open a popup with search result data.

sorry did not get. what you want ?

**Comment by suryapratapsinghsuryavanshi** [comment]
> > I think you make some changes to open a popup with search result data.
> 
> sorry did not get. what you want ?

I think this will help you to understand the issue better,
Link: https://xd.adobe.com/view/3034ede0-57a5-4062-93f0-aa8da7b50923-6567/

**Comment by MuhammadTanveer94** [comment]
> > > I think you make some changes to open a popup with search result data.
> > 
> > 
> > sorry did not get. what you want ?
> 
> I think this will help you to understand the issue better, Link: https://xd.adobe.com/view/3034ede0-57a5-4062-93f0-aa8da7b50923-6567/

ok got it.

**Comment by MuhammadTanveer94** [comment]
for reference
image

**Comment by MuhammadTanveer94** [comment]
now it look ok?

**Comment by suryapratapsinghsuryavanshi** [comment]
Yeah @MuhammadTanveer94 , It looks much better.
Commit your changes we would like to merge them.

**Comment by MuhammadTanveer94** [comment]
> Yeah @MuhammadTanveer94 , It looks much better. Commit your changes we would like to merge them.

@suryapratapsinghsuryavanshi i have commit my change now you can review and merge it.

**Comment by suryapratapsinghsuryavanshi** [comment]
Thanks @MuhammadTanveer94 :)

**Review by suryapratapsinghsuryavanshi — APPROVED** [review]

**Pull request merged**
